.PHONY: clean All

All:
	@echo "----------Building project:[ Learn - Debug ]----------"
	@cd "Learn" && "$(MAKE)" -f  "Learn.mk"
clean:
	@echo "----------Cleaning project:[ Learn - Debug ]----------"
	@cd "Learn" && "$(MAKE)" -f  "Learn.mk" clean
